"""Exact dynamical Lie algebra dimension of the ansatz, computed from the topology.

The generators of the ansatz of Eqs. (11)-(13) are the single-qubit rotations ``X_j, Y_j, Z_j``
on every qubit together with ``Z_j Z_k`` for every active edge (CZ).  Every generator is a Pauli
string, and the commutator of two Pauli strings is zero when they commute and proportional to
their product when they anticommute, so the Lie closure of a set of Pauli strings is obtained by
repeatedly multiplying anticommuting pairs.  The dimension of the real DLA is then the number of
distinct non-identity Pauli strings reached.

Representing a string on ``n`` qubits by the pair of bit masks ``(x, z)`` makes this a small
graph search, exact and fast for the sizes the paper simulates.  It is used to *check numerically*
the two statements that are proved in Lean:

* a topology whose clusters have at most ``b`` qubits has ``dim <= 2 * K * 4 ** b``
  (``CMT.finrank_cmtDLA_le_of_block_count``) -- and in fact exactly
  ``sum_clusters (4 ** |cluster| - 1)``;
* a connected topology has the full ``4 ** n - 1``, i.e. the sparsification removes nothing
  (``CMT.finrank_cmtDLA_ge_of_backwardConnected``, ``CMT.Impl.finrank_cmtDLA_impl_ge``).
"""

from __future__ import annotations

from typing import Dict, List, Sequence, Set, Tuple

from .topology import cluster_labels, cluster_sizes, dla_upper_bound

__all__ = ["pauli_generators", "lie_closure_dimension", "dla_report"]

Edge = Tuple[int, int]
PauliMask = Tuple[int, int]  # (x mask, z mask)


def pauli_generators(n: int, edges: Sequence[Edge]) -> List[PauliMask]:
    """``{X_j, Y_j, Z_j}`` for each qubit plus ``Z_j Z_k`` for each active edge."""
    gens: List[PauliMask] = []
    for q in range(n):
        b = 1 << q
        gens.append((b, 0))  # X
        gens.append((b, b))  # Y (up to phase)
        gens.append((0, b))  # Z
    for j, k in edges:
        gens.append((0, (1 << j) | (1 << k)))  # ZZ
    return gens


def _anticommute(p: PauliMask, q: PauliMask) -> bool:
    (x1, z1), (x2, z2) = p, q
    return ((x1 & z2).bit_count() + (z1 & x2).bit_count()) % 2 == 1


def lie_closure_dimension(n: int, edges: Sequence[Edge], max_dim: int = 1 << 20) -> int:
    """Dimension of the Lie algebra generated by the ansatz generators (exact).

    Raises ``MemoryError`` if the closure exceeds ``max_dim`` elements.
    """
    basis: Set[PauliMask] = set()
    frontier: List[PauliMask] = []
    for g in pauli_generators(n, edges):
        if g not in basis:
            basis.add(g)
            frontier.append(g)
    while frontier:
        p = frontier.pop()
        for q in list(basis):
            if _anticommute(p, q):
                r = (p[0] ^ q[0], p[1] ^ q[1])
                if r != (0, 0) and r not in basis:
                    if len(basis) >= max_dim:
                        raise MemoryError("Lie closure exceeded max_dim")
                    basis.add(r)
                    frontier.append(r)
    return len(basis)


def dla_report(n: int, edges: Sequence[Edge], max_dim: int = 20000) -> Dict:
    """Exact DLA dimension next to the proved bounds, for one topology.

    The closure search is quadratic in the dimension it produces, so the exact computation is
    skipped (and ``dla_dimension_exact`` is ``None``) when the predicted dimension exceeds
    ``max_dim``; the predicted value ``sum_clusters (4**|cluster| - 1)`` and the proved bound are
    always reported.
    """
    labels = cluster_labels(n, edges)
    sizes = cluster_sizes(labels)
    predicted = sum(4 ** s - 1 for s in sizes.values())
    bound = dla_upper_bound(labels)
    exact = lie_closure_dimension(n, edges, max_dim=max_dim) if predicted <= max_dim else None
    return {
        "n_qubits": n,
        "n_edges": len(edges),
        "cluster_sizes": sorted(sizes.values(), reverse=True),
        "dla_dimension_exact": exact,
        "dla_dimension_predicted": predicted,
        "dla_upper_bound_proved": bound,
        "dense_dla": 4 ** n - 1,
        "bound_holds": predicted <= bound and (exact is None or exact <= bound),
        "reduces_dla": predicted < 4 ** n - 1,
    }
